server:
  port: 7080

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.saml: DEBUG
    org.opensaml.xmlsec: DEBUG

spring:
  security:
    saml2:
      relyingparty:
        registration:
          samlple:
            entity-id: smartoffice.kukdo.com
#            entity-id: "{baseUrl}/saml2/service-provider-metadata/{registrationId}"
            acs:
              - location: "http://smartoffice.kukdo.com/saml2/authenticate/ssoLogin.do"
            signing:
              credentials:
                - private-key-location: "classpath:credentials/private.key"
                  certificate-location: "classpath:credentials/public.cer"
            decryption:
              credentials:
                - private-key-location: "classpath:credentials/private.key"
                  certificate-location: "classpath:credentials/public.cer"
            identityprovider:
              entity-id: www.stage.britymail.com
#              metadata-uri: http://localhost:8081/sample-idp/saml/idp/metadata
              singlesignon:
                sign-request: true
                url: https://sso.stage.britymail.com/sso/saml/SingleSignOnService
              verification:
                credentials:
                  - certificate-location: "classpath:credentials/vertication.cer"
